### PR TITLE
Fix/remove role inscribed #20

### LINKED ISSUE #20: Remove :inscribed role
All users coming from CiViCRM will have the `:interested` role by default, so it is no longer necessary to use role in the verification.

~Also, the :role attribute in `config/initializers/civicrm_verification_workflow.rb` should be removed.~

- [x] Remove `:interested` from `User::ROLES`

### PR DESCRIPTION
**Pull request by davidbeig**
This PR closes #20

### CODE REVIEW

File: config/initializers/civicrm_verification_workflow.rb [hunk 1]
```diff
@@ -4,7 +4,6 @@
   workflow.form = "Decidim::Verifications::Civicrm"
 
   workflow.options do |options|
-    options.attribute :role, type: :enum, choices: -> { Decidim::Civicrm::Api::User::ROLES.values.map(&:to_s) }
```
Comment (verarojman) [inline config/initializers/civicrm_verification_workflow.rb:7]: Actually, I messed up writing the issue 🙏🏽  this line should be left as-is, so that admins can restrict actions to users with the `:inscribed` role (to prevent regular `:interested` users from doing certain things)

**Review by verarojman — CHANGES_REQUESTED** [review]

File: config/initializers/civicrm_verification_workflow.rb (hunk 1 above)
Comment (davidbeig) [reply config/initializers/civicrm_verification_workflow.rb:7]: But with the other commit we make sure that there are not :interested roles, right? I thought that we were not going to have any :interested users but only :inscribed

Comment (verarojman) [reply config/initializers/civicrm_verification_workflow.rb:7]: The thing is that these `options.attribute :role` will be used in the admin to restrict actions for users with the `inscribed` role:

image
